### ISSUE TITLE
自动化生成当前需要翻译的文档

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#182]
使用 #167 可以很方便的看到当前还有多少文档没有生成到其他语言。

如果可以用一个机器人/issue追踪这些update就很有效了。

**Comment by chenrui333** [comment]
Is this good enough (leverage Google Translate to cover the languages that we don't have capacity for)?
![image](https://user-images.githubusercontent.com/1580956/74554003-82cc4c80-4f26-11ea-9696-920fd4cdfcf6.png)

**Comment by iLtc** [comment]
The problem is that if the user uses the language switch tool on the right top corner to switch the language, and there is no page for the target language, it will redirect to the home page, which is confusing.

I think what @GindaChen wants to do are 1. automatically generate missing pages for all languages (probably just copy from `en-us` or `zh-cn`), and 2. automatically create issues for untranslated pages.

Google Translate Tool is only for languages that we have not covered yet.

**Comment by GindaChen** [comment]
Exactly. (I will address this once I finish my essays...

**Comment by lovepoem** [comment]
目前看，在i18n里编辑多语言等解决大部分问题了
