### ISSUE TITLE
test self-assign feature

### ISSUE THREAD

**Issue by chenrui333** [wuhan2020/wuhan2020.github.io#210]
relates to https://github.com/wuhan2020/wuhan2020/issues/361
Hypertrons added in this PR, https://github.com/wuhan2020/wuhan2020.github.io/pull/209

**Comment by chenrui333** [comment]
Just duplicate the change in #211 to master branch.

**Comment by chenrui333** [comment]
Give another shot now.

**Comment by GindaChen** [comment]
OK It works now!

**Comment by frank-zsy** [comment]
The function is working now, this bug is related to a GitHub bug(feature?), when @menbotics receives the config file create event, it will try to read the config file on GitHub, but it returns 404 for several minutes which makes it very difficult to init the functions for the repo. We will figure it out later.

Now we need to restart the hypertrons service to make it work.
