### ISSUE TITLE
志愿者证书需求[backend]

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#314]
需求：

1、登入 slack 和填写人才信息时候的邮箱合并起来作为 志愿者邮箱列表（协调组提供）

2、发邮箱到志愿者邮箱，邮件内容为一个链接，点开后在页面提供输入自己姓名和

应该有几个功能：1、后台生成图片  2、发送邮箱功能 3、启动一个web服务，输入邮箱，校验

静态界面：见附件https://github.com/wuhan2020/design-prototype

old issue：https://github.com/wuhan2020/wuhan2020.github.io/issues/298

new repo: https://github.com/wuhan2020/volunteer-certificate

**Comment by lovepoem** [comment]
@pengCC 正在处理中

**Comment by zhaofeng-shu33** [comment]
do we have a backend?

**Comment by zhaofeng-shu33** [comment]
* It is reported that JingDong Cloud will provide the backend server for our community.
* Since we do not know the real names of many volunteers. We use this way to collect their name and send their certificate to their email.
* Firstly we send emails to the volunteers with the content `/zh-cn/certification/index.html?token=abc`. Then the frontend code gets the token and collect the name and email of the user provided in the form. Finally we send the email to the user. The backend code is at [volunteer-certificate](https://github.com/wuhan2020/volunteer-certificate)

**Comment by lovepoem** [comment]
> * Firstly we send emails to the volunteers with the content `/zh-cn/certification/index.html?token=abc`. Then the frontend code gets the token and collect the name and email of the user provided in the form. 

Here the name can be modified , but email cannot be modified

**Comment by zhaofeng-shu33** [comment]
ok
